export const HOME_VIDEO = 'https://hopperhock-ui-assets.s3.amazonaws.com/videos/HopperHockVideo.mp4';
export enum Images {
  HOME_VIDEO_POSTER = '/Images/VideoPoster.png',
  SERVICE_IMAGE_CONTAINER = '/Images/ServiceMainContainer.png',
  NS_COST = '/Images/Home/NSCost.svg',
  NS_CULTURE = '/Images/Home/NSCulture.svg',
  NS_QUALITY = '/Images/Home/NSQuality.svg',
  NS_TIME = '/Images/Home/NSTime.svg',
  NS_TRIPS = '/Images/Home/NSTrips.svg',
  SERVICES_BANNER = '/Images/Services/ServicesBanner.png',
  SERVICES_DESCRIPTION = '/Images/Services/ServicesDescription.svg',
  SERVICES_DESCRIPTION_MOBILE = '/Images/Services/ServicesDescriptionMobile.svg',
  PARALLAX_BANNER_CONTAINER = '/Images/BannerIrregularContainer.svg',
  PARALLAX_BANNER_BACKGROUND = '/Images/BannerBackgroundImage.png',
  SERVICE_WEB_BACKGROUND_WEB = '/Images/ServiceWebBackground.jpg',
  SERVICE_WEB_BACKGROUND_UX = '/Images/ServiceUXBackground.png',
  SERVICE_WEB_BACKGROUND_QA = '/Images/ServiceQABackground.jpeg',
  STACK_SECTION_BACKGROUND = '/Images/TechnologyStackBackground.png',
  STACK_IMAGES_BASE_URL = '/Images/StackImages/',
  WORK_STEPS_BASE_URL = '/Images/Services/WorkSteps/',
  ABOUT_US_INTRODUCTION = '/Images/AboutUs/Introduction/AboutUsIntroduction.svg',
  CB_DESKTOP = '/Images/Services/Capabilities/desktop.svg',
  CB_WEB = '/Images/Services/Capabilities/web.svg',
  CB_MOBILE = '/Images/Services/Capabilities/mobile.svg',
  CB_BACKEND = '/Images/Services/Capabilities/backend.svg',
  CB_UX = '/Images/Services/Capabilities/ux.svg',
  CB_QA = '/Images/Services/Capabilities/qa.svg',
  CONTACT_US_BANNER = '/Images/ContactUs/ContactUsbanner.png',
  CONTACT_US_FORM = '/Images/ContactUs/ContactUsForm.png',
}

export var STACK_IMAGES = [
  'dotnet.svg',
  'java.svg',
  'spring.svg',
  'python.svg',
  'nodejs.png',
  'typescript.svg',
  'javascript.svg',
  'react.svg',
  'angular.svg',
  'nextjs.svg',
  'sass.svg',
  'oracle.svg',
  'sqlserver.svg',
  'postgresql.svg',
  'aws.svg',
];

export var WORK_PROCESS_STEPS = ['Process 1.png', 'Process 3.png', 'Process 5.png', , 'Process 2.png', 'Process 4.png'];
